### ISSUE TITLE
AlgebraicSolving.jl on Windows

### ISSUE THREAD

**Issue by sumiya11** [algebraic-solving/AlgebraicSolving.jl#25]
Hi,

Does AlgebraicSolving.jl work on Windows? (I am getting ```ERROR: UndefVarError: `libmsolve` not defined```)
If not, could you share if you consider to add support for Windows some day in the future?

Thanks !

**Comment by ederc** [comment]
We do not plan to natively support Windows, you can use WSL insteaad.

**Comment by fingolfin** [comment]
@ederc out of curiosity, did you ever try to build it on Yggdrasil for Windows? The build recipe says
```
filter!(!Sys.iswindows, platforms)  # no FLINT_jll available
```
but that's not true (anymore), we do have FLINT for Windows AFAIK.

(I realize this is not a priority, but if it just builds...)
